name: Run Les Mills Pipeline

on:
  workflow_dispatch:

jobs:
  run-dag:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Install Astro CLI
        run: |
          curl -sSL https://install.astronomer.io | sudo bash

      - name: Clean Astro config
        run: rm -rf ~/.astro

      - name: Start Airflow
        run: astro dev start

      - name: Wait for Airflow
        run: sleep 60

      
