name: Run Les Mills Pipeline

on:
  workflow_dispatch:

jobs:
  run-pipeline:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Start Airflow
        run: |
          docker compose up -d

      - name: Wait for Airflow
        run: sleep 60

    
